name: Sync from template
on:
  # Cron job trigger
  schedule:
    - cron: "0 0 1 * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Sync with the template repository
      - name: Sync from template
        uses: AndreasAugustin/actions-template-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: alshedivat/al-folio
          upstream_branch: master  # Or 'main' if the default branch is 'main'

